"""Add password on User

Revision ID: 066cbf1511f4
Revises: e2ca58b5b8f3
Create Date: 2025-09-30 15:18:42.182932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066cbf1511f4'
down_revision = 'e2ca58b5b8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
