"""Add students table

Revision ID: e2ca58b5b8f3
Revises: d5369a4d4b76
Create Date: 2025-09-23 16:10:40.939863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ca58b5b8f3'
down_revision = 'd5369a4d4b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.String(length=32), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_fullname'), ['fullname'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_nisn'), ['nisn'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_nisn'))
        batch_op.drop_index(batch_op.f('ix_students_fullname'))

    op.drop_table('students')
    # ### end Alembic commands ###
